name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    uses: divmora/.github/.github/workflows/pages-deploy.yml@main
    with:
      artifact-path: './docs'
